FROM mcr.microsoft.com/devcontainers/python:0-3.11

# Install git (useful for editable installs and development)
# RUN apt-get update && apt-get install -y --no-install-recommends git && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
